name: Test deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: nix-shell -p yarn --run "yarn install --frozen-lockfile"

      - name: Test Build
        run: nix-shell -p yarn --run "yarn build"
